workflows:
  my-workflow:
    environment:
      groups:
        - firebase_credentials
    publishing:
      firebase:
        firebase_token: $FIREBASE_TOKEN
        android:
          app_id: 1:381890950140:android:8d8d2fa040e306b3abf879
          groups:
            - androidTesters
            - ...
          artifact_type: "apk"
