workflows:
  my-workflow:
    publishing:
      firebase:
        firebase_token: $FIREBASE_TOKEN
        android:
          app_id: x:xxxxxxxxxxxx:android:xxxxxxxxxxxxxxxxxxxxxx
          groups:
            - androidTesters
            - ...
          artifact_type: "apk"
