workflows:
  my-workflow:
    scripts:
      - name: Publish to Firebase Hosting
        script: |
          firebase deploy --token "$FIREBASE_TOKEN"
    environment:
      groups:
        - firebase_credentials
    publishing:
      firebase:
        firebase_token: $FIREBASE_TOKEN
        android:
          app_id: larsapp-8d316
          groups:
            - androidTesters
            - ...
          artifact_type: "apk"
